### ISSUE TITLE
demo似乎有问题

### ISSUE THREAD

**Issue by ximlu** [kayanouriko/jsc-require-swift#1]
我再执行demo时 sayHello 没有执行，不知道是bug还是其他什么原因

**Comment by kayanouriko** [comment]
以前只有 js 代码块需要用 oc block 去桥接, 现在不知道是不是改了接口, 连原生处理逻辑也需要桥接了.

https://github.com/kayanouriko/jsc-require-swift/blob/8fdf81e019e6240a3576f48d103a7686c2c45ca3/JavascriptCoreDemo/JavascriptCoreDemo/extensions/JSContext-Extensions.swift#L21

这里的代码改成即可

```swift
let callback: @convention(block) (String) -> JSValue = { jsName in
    // 实现逻辑
}
```

当然, 我也没有细研究, 不知道 JavaScriptCore 现在有没有纯 Swift 的实现方式, 你自行研究吧.

> 注意: 这个 demo 只是提供思路, require 和 console.log 的实现都是很简陋的, 不能用于实际生产.
